org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# AGP 8.3.2 + Kotlin 1.9.23 需要 JDK 17~21（请按自己机器修改此路径）
org.gradle.java.home=C:/Users/Ray/.vscode/extensions/redhat.java-1.56.0-win32-x64/jre/21.0.12.1-win32-x86_64
android.overridePathCheck=true
